### ISSUE TITLE
Comprehensive UML Diagram Creation for System Design

### ISSUE THREAD

**Issue by marcinwolder** [marcinwolder/InzynieriaOprogramowania#32]
### Description:

The task involves creating comprehensive UML diagrams for the designed system. This includes diagrams such as Use Case Diagrams and Sequence Diagrams that accurately represent the system's functionality, behavior, and interactions.

### Steps:

1. Identify and document all the use cases of the system:
   - Define the primary actors interacting with the system.
   - Specify their goals and the interactions required to achieve these goals.
   
2. Create a Use Case Diagram:
   - Represent actors and their interactions with the system.
   - Group use cases logically for clarity.

3. Identify key sequences in the system's operation:
   - Select core functionalities or scenarios for which sequence diagrams need to be created.
   - Define the roles of objects and actors involved in these scenarios.

4. Create Sequence Diagrams:
   - Represent the order of interactions between objects and actors in a detailed step-by-step manner.
   - Include relevant details like lifelines, messages, activations, and conditions.

5. Review and refine the diagrams:
   - Ensure consistency between different UML diagrams.
   - Verify that all system functionalities are accurately represented.

### Output:

- A Use Case Diagram showing all actors and their interactions with the system.
- A set of Sequence Diagrams illustrating key scenarios and interactions within the system.

**Comment by epetrycka** [comment]
I have created the diagrams, except for the user account management, the subscription and payment management diagrams.
